---
title: "MP2"
author: "Katelyn Diaz, Salwa Ouachtouki, Jiselle Ramirez, AJ Haller"
date: "`r Sys.Date()`"
output: openintro::lab_report
---


```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(readr)
library(car)
library(ELMR) # can handle the missing data
```

```{r setup, message = FALSE, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE, 
  warning = FALSE
)
```

```{r Data Wrangling}
data <- read.csv("SDS290_MP2.csv")

data <- data[-c(1:2),] #removing top two rows
# Turning characters into integers
data$Date_1<- as.integer(data$Date_1)
data$Date_2<- as.integer(data$Date_2)
data$Date_3<- as.integer(data$Date_3)


# For those who are attracted to either but got a woman profile
data$Core_Attraction[data$ResponseId == "R_V2UevjhK4UnPmy5"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_6xHhUJhk696WyB3"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3kmGSOrdAk5puSH"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3pcfqpTHnRV7Cju"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_290J1qA5xIQg2mK"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_2dNpwMPlUQACxmd"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_274eaoafNmrPYnp"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3Hny656zgvdHb2s"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_2wLWhXn3EDCJqPn"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3noXNPFgToZbWh1"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3FV7p5fr0afhDD5"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_ze5FVlED54G4cet"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3EVTj66CowfcUb4"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_3KOfLuDutKd6qc1"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_2ayGRcFcYWK0jRi"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_272JPXVYATqLUbz"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_1JKpV4XnhKXFjqe"]<- "Women"
data$Core_Attraction[data$ResponseId == "R_274eaoafNmrPYnp"]<- "Women"

# For those who are attracted to either but got a man's profile
data$Core_Attraction[data$ResponseId == "R_2rueH05SuYZgIn0"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_1QxqvQ0KrK7xjR0"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_b7cIT65mNhTfcBP"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_1fl9qMkhZzjmf0a"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_1Caa5kDquAnIXyo"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_1ODCSbsXgXzLEUm"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_RDdoh3MZRv7d3Pz"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_3nV0ZXsUDhsr3Lw"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2t2K6YtKnOY7bPB"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_3j3w5WOyhLFIZDM"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2CDozL5RSFEgjtu"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2D8Eyyj1qcYfgBw"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2YmJ5ZkpIGVMe8G"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2v2s0qn6mhFEl8O"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_1DDedD5Wz8gulRZ"]<- "Men"
data$Core_Attraction[data$ResponseId == "R_2X4MIZmcPZIKndZ"]<- "Men"

data <- data %>%
  select(ResponseId, Gender, Core_Attraction, Sexual_Orientation, Date_1, Date_2, Date_3, App, Bio) %>%
  na.omit() %>%
  filter(!is.na(Gender))%>% #removed completely empty rows
  mutate(attraction = (Date_1+Date_2+Date_3)/3) %>% 
  filter(Core_Attraction != "Either")


#RAW ALPHA
alpha(select(data, Date_1, Date_2, Date_3))

```

```{r}
#Exploratory Visualizations

ggplot(data, aes(x = App, y = attraction, fill = Bio)) + 
  geom_boxplot()+ 
  facet_wrap(~Core_Attraction)

ggplot(data, aes(x = App, y = attraction, color = Bio)) +
  geom_point() +
  geom_jitter()  + 
  facet_wrap(~Core_Attraction)
```

## Conditions

C and A can be assumed.

```{r}
ds <- data %>%
  group_by(App, Bio, Core_Attraction) %>%
  summarise(n = n(),
            mean = mean(attraction),
            sd = sd(attraction)
  )
ds

ds %>% 
  ungroup() %>%
  summarise(max(sd)/min(sd))


leveneTest(attraction ~ App*Bio*Core_Attraction, data = data)


# Using Levene’s Test for homogeneity of variance, we fail to reject the null hypothesis, that is we fail to find evidence that the S condition is not met, F(7,144)=1.0155, p=0.4229. We can proceed as if this condition is met.

#Variances are equal
```

### Formal Analysis without interaction

```{r}
mod <- lm(attraction ~ App + Bio + Core_Attraction, data = data)
anova(mod)

#Not Significant

```
 


### Checking for Interaction

```{r}
ggplot(data, aes(x = App, y = attraction, 
                    group = Bio, 
                    color = Bio)) +
  geom_point() +
  geom_smooth(method = "lm", se = 0) + 
  facet_wrap(~Core_Attraction)
#   geom_jitter()

#Slight interaction

#No interaction for men
#Slight interaction for women

#for men<- No main effect of Bio but slight main effect for App
#for woman<- No main effect of App but slight main effect for Bio
```

### Two way Anova

```{r}
mod_int <- lm(attraction ~ App + Bio + Core_Attraction + App*Bio + Core_Attraction*Bio + App*Bio*Core_Attraction, data = data)
anova(mod_int)

#Not Significant
```

```{r}
# N and Z
qplot(x = mod_int$residuals, bins = 5)
plot(mod_int, which = 2)
plot(mod_int, which = 1)

```

None of our hypotheses were correct.

### Confidence intervals and Effect sizes

```{r}
data_women<- data %>%
  filter(Core_Attraction == "Women")


mod <- aov(attraction ~ App*Bio, data = data_women)
TukeyHSD(mod)


# Based on Tukey's HSD, the differences between different apps and different bios are not significant because our confidence intervals include zero
```



